name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install Dependencies
        run: yarn install --immutable
      - name: Validate dependency tree
        run: yarn workspaces foreach -t run build
      - name: Config Git User
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Release Bot"
          git remote set-url origin https://$GITHUB_ACTOR:$NPM_TOKEN@github.com/s-ong-c/changeset-test
        env:
          GH_TOKEN: ${{ secrets.GA_MVN_PUB_GITHUB_TOKEN }}
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: yarn release
          commit: "ci(changesets): version packages"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
